---
  copyright_image:  https://i.creativecommons.org/l/by/4.0/80x15.png
  copyright_image_link: http://creativecommons.org/licenses/by/4.0 
  copyright_text: "Unless otherwise noted (e.g. image licenses may vary) all content is licensed under a Creative Commons Attribution 4.0 International License. (CC-BY)"
