---
  header_logo_url: http://aphid.archive.speciesfile.org/HomePage/Aphid/img_Logo/SiteLogo.jpg
  header_logo_text: 'Aphid Species File'
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
