---
  project_name: 'Aphid Species File'
  project_citation: 'Aphid Species File'
  project_authors: 'Colin FAVRET'
  project_url: 'https://Aphid.SpeciesFile.org'
  project_old_url: 'https://Aphid.Archive.SpeciesFile.org'
  focal_taxon: 'aphids'
  focal_taxon_common_name: 'adelgids, blackflies, greenflies, plant lice, and phylloxerans'
  contact_email: 'ColinFavret@AphidNet.org'
  copyright_text: 'Aphid Species File is an open source, open access, project. Its entirety is offered to the Public Domain, although an attribution or citation would be appreciated.'
