---
  project_name: 'Aphid Species File'
  project_citation: 'Aphid Species File'
  project_authors: 'Favret C.'
  project_url: 'https://aphid.speciesfile.org'
  project_old_url: 'https://aphid.archive.speciesfile.org'
  focal_taxon: 'aphid'
  focal_taxon_common_name: 'greenfly, blackfly, and plant lice'
  contact_email: 'ColinFavret@aphidnet.org'
